# Generated by Django 4.2.2 on 2023-06-22 20:15

from django.db import migrations
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_aisle_user_unit_user_alter_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='aisle',
            field=recipes.models.CustomForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.aisle'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=recipes.models.CustomForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.unit'),
        ),
    ]
